name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

defaults:
  run:
    # Replace 'your-folder-name' with the exact name of your uploaded folder
    working-directory: ./MP3_TAG_READ_EDIT

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: configure
      run: ./configure
      
    - name: make
      run: make
      
    - name: make check
      run: make check
      
    - name: make distcheck
      run: make distcheck

    - name: Run the Code
      # Replace 'your_executable_name' with the actual name of your output file
      run: ./mp3_tg_re
